addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- cd src
- ../binaries/hugo --theme=academic
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github-token: $GITHUB_TOKEN
  on:
    branch: master
