addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- cd src
- ../binaries/hugo
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  on:
    branch: master
env:
  global:
    secure: S/VjwHGfs1RQf1Rj5QIXWqej8k8xr28K5ETbLhRmn+fNP0yocjdJ6nxhHv9SDUhWq+176CdiLZbaEZGHM7B/yWlppXisUJIoiG5LlD/pvAehqFyo2oRGElHrA+RAjNEJ0TOs1+WzZ2gpEQ8lXCysaWo+N1wugTA1fHqAqYxT9hjvNCL7NzArsjUb80Rig35pY8OHa8bkQGBXh6mwemKFBUV4sqREkp6MRnV+69ujemJ71OhfjhSS1lRqucmzWWA6VjoySFdnmbYZ01MbF1EJOTgZ4yzK44XKORNka92k7KGD9Iatt9YAOFs26sNxvnZ6uoJC+V+ncreo/bkBwad7v3q7lVKqmMZLkYDMingyYG5crZtjbSK9/immPSuWsInJLWQgspdxgb/d24M33rJazvLExRHlmhW7dirRugPaciPRZbxGdK0Qb6wxwA3crbKxWR8gbeFmkHDLmCy7O3iqcqdDWOTXZnquE5GFOcCtOUYV+qBxK6yjrVrq/ViOwmkQ1/1XC1hyRRhpCWSVyLGnwvtVYqwS5hzG1eCmy68fxAGwI7bD6N0R64RMU1OUR1xHDB6VFUsLacggMTMghf9IBAnPletEOXqP7RkKeSSZ60IYsthEJF252+Ggabz4a2Ak497v383gfYzWlEgUqv5VwKY8YwJtH27zI+1ECb5mh54=
