addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- cd src
- ../binaries/hugo
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
env:
  global:
    secure: Thkmz7lFqUSg2w8P2pdS0HcC5KHLNYZ4kNUqR9PVJ7W12UQb6NH3cWGBXRauIvA5QPWr5oB63N0c8ZWWL3wqqMPKbT/XVBFJxDAkAjj+sehGmgNDNm3U1B3AyNw+HHo/XX5FNvuhBGZmViikcDgXYXFqrUL6j52lOqLrrZk/xx3bDHk/lvgvzwk4nUQd4/yscT5c/KQVDNTUMXnhfmXGO2mj7M+1/DgO8HXgZw2sUGA0t8SdA+/ePVk7yjBdSB6srYeGil66SV92qOj7/Y5e8EdaRueZBu3434NN0tfY0ZfjVN1dG5pKxuhEFoGn4J20cDA5QsS8TWaNOPZscROeQGv9eBS54JaqzzSZPCKn2lDxfzhmZDe2vUk8B7ZxPvh3NBq63J7pKW+4h4a867kshwuPhFZNEcy/0k4alnd8h+xd4UPtPkiWdzO8jQf0cMx+XP0cqFczlJJeaWa/SNy+M2c99fMacFF7D9hoG8ypogMYxLHNxOqxJllXibVbwcBJVIfO9t3xZn9/Q8UpzDSMhxmiIvz52Z/1nuQHDvmUPvT8qEy4pMlbkM4h8rJMoFWjzCN5j9JpblVvZTi7vujmIz72V1p77OXZkqADoON7ioAnqBpCE7B31W+FDR891h0cJAYX3xcfHjxNXaYAT7JkSj8uXvrOTceaGe0zRBUVsXQ=
