addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- cd src
- ../binaries/hugo
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  on:
    branch: master
