addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- cd src
- ../binaries/hugo
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  on:
    branch: master
env:
  global:
    secure: Bdz3QRhz4YLYpol/1ThRyQdi8r8+cRk2RWEyj+agadkuhplTidM7w4QdG4BNUZleGBVNxV7yT+8t0y5w63Z+q5asyb8o2szd+Ii+/DlZ4BL0NP6dzHTm+AYjHdYSnWZ9Kmnb4ALkMQJdU2ov6a1Yrq72VUQwxsnjF4Ea1G3AE1bgqRGCxhEUK7k+yIHQOk6U1edS32EL+geLRkgdHfieFxBySb17hpuNUDxo8go565t1ADUucbbD+tlM6hupuKhD67jzzGmD7tzfvnq39zUlaV5dM77kQXK/AGnYqAqUIW6W6hdvGyLxuPXbEmKaVdp8AQHuBbQBrRtIU4FIQAa/e4fE27Df3UEV9kAFkQEHXltxaCJ4RHDMHKID4dgfW9xs3amaO/d0XTVIfKHYFaHg+4TtkrHF1Of46sQ/on00iUypO4n/tO8THkDzNXSsitDP4vXrJmZAxGLPAgxZV1wBTyIIO+lUoMPSO3oqa2lFqkmEPqZB54xm7bIlaeenWTpGhlKmCkLzsRxU+Q1DJDsqtPk6IHxHHVkbZAT919BEdNxtbPb+RCaJI9G4g9r/X5oc2q08UPLMlVn1IHLFgQy25Bpz5IDonKBVWz6JeZKRIL+D0cMTIpmcnh+cqaqHuQPmUMeL/R5vNPo0yVhB3cbsmq7Lnsa3UDCEu0kXkUTM3sA=
